sudo: false
language: node_js
node_js:
  - "6"
cache:
  directories:
    - node_modules # NPM packages
script: npm run lint
# To be able to build bcrypt and other modules which may depend on C++/C++-11
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
